### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by coursar** [sebastyanpereira/web-app#2]
Добавить во все jsp (кроме бутстрапа):
`<%@ page contentType="text/html;charset=UTF-8" language="java" %>`, чтобы с русским было Ok.

**Comment by sebastyanpereira** [comment]
@coursar а в этих jsp уже вроде как она есть, другие jsp это бутстрап

https://github.com/sebastyanpereira/web-app/blob/78c15cfea2cf70db951093a0ef73f47cda2cf198/src/main/webapp/WEB-INF/catalog.jsp#L3

https://github.com/sebastyanpereira/web-app/blob/78c15cfea2cf70db951093a0ef73f47cda2cf198/src/main/webapp/WEB-INF/error.jsp#L1

**Comment by coursar** [comment]
Ок, тогда посмотрите как в сам запрос добавить: https://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#setCharacterEncoding(java.lang.String) вам нужно "UTF-8" (должно быть первым вызовом)
